/* tslint:disable */
/* eslint-disable */
/**
 * lyubishevtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddTimeEventRequest
 */
export interface AddTimeEventRequest {
  /**
   *
   * @type {number}
   * @memberof AddTimeEventRequest
   */
  tagId: number;
  /**
   *
   * @type {string}
   * @memberof AddTimeEventRequest
   */
  date: string;
  /**
   *
   * @type {string}
   * @memberof AddTimeEventRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AddTimeEventRequest
   */
  startTime: string;
  /**
   *
   * @type {number}
   * @memberof AddTimeEventRequest
   */
  minute: number;
}
