/* tslint:disable */
/* eslint-disable */
/**
 * lyubishevtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CurrentUserResponse
 */
export interface CurrentUserResponse {
  /**
   *
   * @type {number}
   * @memberof CurrentUserResponse
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof CurrentUserResponse
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof CurrentUserResponse
   */
  nickname: string;
  /**
   *
   * @type {string}
   * @memberof CurrentUserResponse
   */
  photoUrl: string | null;
  /**
   *
   * @type {string}
   * @memberof CurrentUserResponse
   */
  token: string;
}
