/* tslint:disable */
/* eslint-disable */
/**
 * lyubishevtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TimeEvent } from "./time-event";

/**
 *
 * @export
 * @interface ListOneDayTimeEventResponse
 */
export interface ListOneDayTimeEventResponse {
  /**
   *
   * @type {Array<TimeEvent>}
   * @memberof ListOneDayTimeEventResponse
   */
  timeEvents: Array<TimeEvent>;
}
