/* tslint:disable */
/* eslint-disable */
/**
 * lyubishevtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TimeEventTagColor } from "./time-event-tag-color";

/**
 *
 * @export
 * @interface TimeEventTag
 */
export interface TimeEventTag {
  /**
   *
   * @type {number}
   * @memberof TimeEventTag
   */
  id: number;
  /**
   *
   * @type {TimeEventTagColor}
   * @memberof TimeEventTag
   */
  color: TimeEventTagColor;
  /**
   *
   * @type {string}
   * @memberof TimeEventTag
   */
  name: string;
}
